version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - ./db:/data/db
