on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & install Dependancies
        uses: ./.github/actions/install_dep
      - name: Build
        run: npm run build
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & install Dependancies
        uses: ./.github/actions/install_dep
      - name: Lint
        run: npm run lint
